#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/config/bootstrap.php');

// Merge global and local configs
$config = require(__DIR__ . '/config/console.php');
$localConfigPath = __DIR__ . '/config/local/console.php';

if (file_exists($localConfigPath)) {
    $localConfig = require($localConfigPath);
    $config = \yii\helpers\BaseArrayHelper::merge($config, $localConfig);
}

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
